# Generated by Django 2.2 on 2019-04-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('GPIO', 'GPIO Device')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('DEGC', 'Celcius'), ('DEGF', 'Farenheit'), ('UNITLESS', 'Unitless')], max_length=10)),
                ('variable_measured', models.CharField(choices=[('T', 'Temperature'), ('SG', 'Specific Gravity')], max_length=10)),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='api.Fermentation')),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='api.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('start_effect', models.DateTimeField()),
                ('end_effect', models.DateTimeField()),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=12)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='api.Dataset')),
                ('output_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='api.Device')),
            ],
        ),
    ]
