# Generated by Django 2.2.1 on 2019-06-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='unit',
            field=models.CharField(choices=[('DEGC', 'Degrees Celcius'), ('DEGF', 'Degrees Farenheit'), ('UNITLESS', 'Unitless')], max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('GPIO', 'GPIO Device'), ('BLE', 'Bluetooth Low Energy Device')], max_length=10),
        ),
    ]
