# Generated by Django 2.2.2 on 2019-06-14 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataset_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='logging_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_datasets', to='api.Device'),
        ),
    ]
